apiVersion: 1

apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false
    
    secureJsonData:
      saToken: ''

    jsonData:
      appUrl: https://localhost:3000
      orientation: portrait
      layout: simple
      dashboardMode: full
      timeZone: ''
      logo: ''
      maxRenderWorkers: 2
      persistData: false
